### ISSUE TITLE
Authorize Scala Play Server against the Instance Registry

### ISSUE THREAD

**Issue by janniclas** [delphi-hub/delphi-management#105]
**Feature**

After version 0.8.0 the instance registry introduced an authorization / authentication scheme for all components communicating with it and each other. 
The scala play server needs to support this feature too in order to be able to communicate with the ir and the other components. Therefore, first the implementation of the registry has to analyzed with @johannesduesing to decide how to integrate that on our side.

**Comment by Ayybeeshafi** [comment]
Hi @janniclas 
I've looked into the feature and its implementation in IR. I've also discussed it with Johannes. I believe I can get the task done on my own. If I come across issues I intend to seek help from @sami-cseseu as he as prior experience in Scala play and working on the IR end of Authorization.

According to my understanding, we have to first generate a JWT key on Delphi Management end for each user, authorise it with username and password at IR and send it back. Once a user is authorised each request to IR is first checked at Delphi Management end if it is triggered by an authorised user. If Yes it is proceeded otherwise denied.
@johannesduesing Please add to it if I am missing something or correct me if I am wrong.

**Comment by janniclas** [comment]
hey @Ayybeeshafi ,
I believe you are mixing up some tasks here. 
As discussed the authorization should take place in two steps. 
1. as described in this issue we need the backend of delphi-management to authorize against the delphi-registry (since management is a normal component in the system the same way as the crawler, webapi, and webapp are). 
2. later we want to add the user authorization to the implementation as described in a different issue.

Regarding your understanding of the concerns:
To my understanding we don't want to generate a JWT key in the management backend. This is already done in the instance registry. We have to include an application secret in the management backend with which we identify the management against the instance-registry. We send this secret to the registry and receive a JWT token as a response. 
This token can then be used to further authenticate every further communication between the management and the registry.

Once this is implemented we can have a look into the issue regarding the user management and authorization.

@johannesduesing feel free to add anything I might have forgotten or misunderstood myself.

**Comment by johannesduesing** [comment]
That's seems about right to me. The steps at @Ayybeeshafi has to take should be something like this:

1. Add a configuration value like ```JwtSecretKey``` to the management application's configuration file
2. Add a method that calls the ```/authenticate``` endpoint of the registry. 
      - The input parameters for your method are the username and password of the management user
      - Your method will put ```<username>:<password>``` into the ```Authorization``` HTTP-Header of the request
      - Your method will put a valid JWT generated for the management *component* using the ```JwtSecretKey``` into another Header called something like ```Delphi-Authorization``` (please sync yourself with @sami-cseseu to determine an appropriate name for this header)
      - Your method will read the response from the registry, which is a valid JWT for the *user*, and return it

**Comment by Ayybeeshafi** [comment]
Thank you for the clarification. I am on it.
