### ISSUE TITLE
User Authentication (simple username/password login)

### ISSUE THREAD

**Issue by janniclas** [delphi-hub/delphi-management#117]
**Feature**
The current Landingpage should be replaced by a basic login mask in which the user can provide a username and password.

**Data flow scheme for Authentication**

1. The username & password should be send to a (new) authenticate endpoint of the scala play webserver.
2. On the scala play webserver a component token is added to the request and it is forwarded to the authorization endpoint of the instance registry.
3. The ir responds with a user token, which is send as a response to the client
4. The client stores the user token and appends it to every request as needed

@johannesduesing what is the lifetime of the user token and do you have a plan in place to refresh the user token?

@Ayybeeshafi will handle the extensions needed on the server side, while I will make the necessary extensions in the api service of the frontend. 
@ishwaryaPaderborn if you like you could provide a design for a login page (do we already have something like this in place?)

**Comment by janniclas** [comment]
In the currently proposed solution the endpoints of the management webserver would be protected with the user token and this server would do the request filtering and only forward the valid requests to the instance registry. 
An alternative would be to append the user token to the requests to the registry and let it handle the validation there.
Currently, I would suggest to let the management server do the validation of the user tokens.
In a long run, when we start to include different user roles, it will most likely be a good idea to include a standalone authorization service for the overall authentication stuff and role management.

As our security expert, @bhermann do you have anything to add or further suggestions to this proposal?

**Comment by Ayybeeshafi** [comment]
I have implemented a method that invocates user/authenticate endpoint. It sends two headers(Basic Authentication and Delphi management JWT token). As a response IR returns a token.

Till now there is no method to check my side of the code. Although, if two headers are sent via Postman in a POST request the IR successfully returns a token as in the following screenshot.
![basicauth](https://user-images.githubusercontent.com/34144308/52903830-96fe4080-3223-11e9-89c1-463e7f566218.png)


Furthermore, there are some prerequisites for IR to process the user/authenticate request.

-  Your system must have mysql installed and running.
- You need to create a database for user authentication on your local machine (e.g. userAuth)
- in Configuration.scala file of IR. Change useInMemoryAuthDB = false and add DB name along with username and password of your mysql.

**Comment by janniclas** [comment]
hey @Ayybeeshafi thx for your work, the code looks good so far (I've made a tiny comment to the last commit tho). 

I would like to ask you to extend your authorization object with a method to validate the correctness of a given token. 
As @johannesduesing explained to me the user token, which is created on the instance registry, can be validated on the backend of the management. The workflow, as described in this issue, would suggest that we include the user token in every request from the frontend to the backend of the management. The token can then be checked in the management and only the valid requests will be forwarded to the instance registry. 
The validation could be implemented in the authorization object you designed. I would expect this method to take a token as input (which would be included in the authorization header of each request), validates the token and returns the result of the validation check. 
If the check was successfull the existing code in the instance registry controller would be executed, else a 403 forbidden should be returned.

**Comment by johannesduesing** [comment]
The duration that a user token is valid for can be configured in the registry's configuration file, the default duration is 30 minutes. We do not have any mechanisms in place to deal with refreshing the token. What i would suggest is in the management backend to check whether a token is still valid, and if not redirect the user to the login page. 

@janniclas what do you think of that ?

**Comment by janniclas** [comment]
hey @johannesduesing, I think for a first version of a basic user authorization this will be feasible, but in the long run we need some kind of refresh token to keep the user logged in. 
I'm thinking about the use case in which we want to use the graph view of the management on a huge screen in front of @bhermann office to show the system's state at all times. This would only work for 30 minutes without a refresh token.

**Comment by ishwaryaPaderborn** [comment]
@janniclas I dont think we already have a 'Login' form. I think we just had a user profile created few months back. But because it was not of higher priority that time I removed it. hence, I will create a login form with required fields.

**Comment by janniclas** [comment]
This article describes the basic http interceptor method I'm implementing in our code right now. I plan to chain this with route guards to not only protect the api requests but also keep the user from navigating away from the login page without being logged in https://blog.angular-university.io/angular-jwt-authentication/

**Comment by bhermann** [comment]
> In the currently proposed solution the endpoints of the management webserver would be protected with the user token and this server would do the request filtering and only forward the valid requests to the instance registry.
> An alternative would be to append the user token to the requests to the registry and let it handle the validation there.
> Currently, I would suggest to let the management server do the validation of the user tokens.
> In a long run, when we start to include different user roles, it will most likely be a good idea to include a standalone authorization service for the overall authentication stuff and role management.
> 
> As our security expert, @bhermann do you have anything to add or further suggestions to this proposal?

Sorry for the late reply... just seen this. Yes, I agree with this assessment.

**Comment by bhermann** [comment]
Could you post a screenshot of the Login form or a picture of the draft here?

**Comment by Ayybeeshafi** [comment]
Hi @johannesduesing . Since Jan is away I thought I should clear my concerns with you. Whenever you have time you can get back to me on this.

First thing, I have to create a middleware that verifies the token is valid using isValid() before processing any request e.g.  postInstance() /instance/deploy.
I have looked into how to implement a middleware that checks if the token received is valid before moving on to the request. I think I have to create reusable custom action by using ActionBulder that authenticates the each subsequent request and verifies the JWT in order to permit the request to access the corresponding service.

Secondly, I was wondering if we need this additional layer of security.

- As the backend first verifies if the request has valid JWT token in its header before processing it.
- We are also checking if the token received after userAuthentication is valid at the frontend.
- Our concern is if anyone can make a request to Instance Registry via curl etc. Curl request also requires a valid JWT token in order for a request to be processed.

**Comment by johannesduesing** [comment]
Hey @Ayybeeshafi , 
i'm not quite sure if i understood your question, but maybe i can try to clarify that. I guess that what you want to do is check whether the Access Token sent from Frontend to Backend is valid before sending any request to the registry, is that right?
And if it's not valid anymore you want the backend to return ```401 Unauthorized```, so that the frontend knows the token is expired and can either redirect the user to the login page or, once supported, use the refresh-token to acquire a new access-token.

It's true that the registry also checks the token and would return 401 if the token is expired. But if you do not check it in the Backend as well, you would have to change every Backend method that is calling the registry to check for return code 401, and then replicate this response to the frontend. To me, this is not a good way of dealing with that issue, and it would produce a lot of duplicated code.
I think what @janniclas was hoping is that you would be able to create *one* method that checks the token, and find a way to make the Play framework apply this method to all routes that may be called by the frontend (something like a *"Route-Guard"*). This would reduce the necessary changes to a minimum and would be the ideal solution for this scenario. Unfortuntely i'm the opposite of an expert on Scala Play and do not know how this is possible :smile:  I just read [this](http://fizzylogic.nl/2016/11/27/authorize-access-to-your-play-application-using-action-builders-and-action-functions/) article and think that these ActionBuilders may be the thing you are looking for here.

**Comment by Ayybeeshafi** [comment]
Hi @janniclas . You can find implementation of a middleware that checks if user is authenticated before moving on to the actual method in the branch feature/UserAuthEndpoint
There are few issues in it that are needed to be addressed first.

- I am unable to debug an issue with ActionBuilder class that is asking for a second parameter BodyParser. I have tried different solutions, nothing seems to work.
- Second, It seems impossible to extract and access the token received in body.response outside the method.  smile

If you find sometime in the next couple of days. Give it a look. Otherwise, we can sit together on Thursday in order to find a working solution.

**Comment by janniclas** [comment]
hey @Ayybeeshafi ,
could you please point me to where I can find your implementation? Are you referring to the action builder code commented in the AuthProvider? Are there any further changes I should have a look at in other files? :)

**Comment by Ayybeeshafi** [comment]
No. The action builder at the end of Instance Registry Controller.
Under the authentication method. 
Other change that I made was to add authentication.async in getNetwork() endpoint instead of Action.async.
