### ISSUE TITLE
Extended ScalaStyle Coding Conventions

### ISSUE THREAD

**Issue by janniclas** [delphi-hub/delphi-management#28]
We are currently implementing an automated scala style checker to ease the coding process as discussed in the last project group meeting. 

Until now the style checker's checks are mainly based on the default config, with the plan to extend and alter these settings as the project grows and we can see which rules work for us and which won't. 

Nonetheless we want to enforce some additional coding conventions not explicitly enforced by the stylechecker. In the following I present a short overview of example decisions for general coding style I came up with. 

- enforce variable names to be started with a small letter (variable)
- enforce constant names to be in capslock (CONSTANT)
- decide on camelCase vs underscore (camel_case)

I want to use this issue to discuss, which options we want to use and to be able to provide additional suggestions for new coding conventions. 

@bhermann since you are currently the main contributor to the delphi project, and are most familiar with scala I have assigned this issue to you. I would like to ask you to check our decisions after the discussion is finished and make sure that they match your expectations.

**Comment by bhermann** [comment]
Quick answer: Camel Case in everything: variable names start with lower case letter, constants with an upper case letter. 
See: https://docs.scala-lang.org/style/naming-conventions.html

**Comment by johannesduesing** [comment]
If this is common practice and used throughout all of Delphi already we should definitely settle for that. Since we do not have much experience with Scala at all, I see no point in bringing our own tastes into the style guidelines for this particular point, as it would require us to adapt all of the existing code.

**Comment by Ayybeeshafi** [comment]
Although I don't have much experience with Scala. So I have looked into web and found the following useful coding style preferences that we should adopt for making our code easy to understand and more efficient.

**Prefer `URI` over `URL`**
When storing the URL of a service, you should use the URI representation. As the equality check of URL performs a blocking network call to resolve the IP address.

**Prefer Existing Well Tested Methods:**
When there is an existing well-tesed method and it doesn't cause any performance issue, prefer to use it. Reimplementing such method may introduce bugs and requires spending time testing it.

**Prefer `null` over `Option`**
For performance sensitive code, prefer `null` over `Option`, in order to avoid virtual method calls and boxing. Label the nullable fields clearly with Nullable.

**Private Fields**
Variables with `private` datatype are still accessible by other instances of the same class. Make the field `private[this]` instead.
```
// The following is still unsafe.
class Foo {
  private var count: Int = 0
}

// The following is safe.
class Foo {
  private[this] var count: Int = 0
```
Pattern Matching:
For the methods whose entire body is a pattern match expression, put the match on the same line as the method declaration.

**Curly Braces:**
Put curly braces even around one-line conditional or loop statements.
```
// Correct:
if (true) {
  println("Wow!")
}

// Correct:
if (true) statement1 else statement2
// Wrong:
if (true)
  println("Wow!")
```
**Rule of 30**
"If an element consists of more than 30 subelements, it is highly probable that there is a serious problem" - [Source](http://swreflections.blogspot.de/2012/12/rule-of-30-when-is-method-class-or.html).

In general:
A method should contain less than 30 lines of code.

**Comment by johannesduesing** [comment]
I would agree to most of these rules, but i have read something different about the usage of null. In the scalstyle rule justification it says "Scala discourages use of nulls, preferring Option" (http://www.scalastyle.org/rules-1.0.0.html#org_scalastyle_scalariform_NullChecker).

**Comment by bhermann** [comment]
I was also wondering how you all feel about the VarLocalChecker:
http://www.scalastyle.org/rules-1.0.0.html#org_scalastyle_scalariform_VarLocalChecker

**Comment by janniclas** [comment]
in general I would like to use the pattern enforced by the VarLocalChecker, because I think it is a good practice to use. 
I am just wondering if it might get annoying at some use cases if it is always enforced and leads to unnecessary code? I believe I have once been annoyed by a similar rule when working with typescript, I have to double check what was going on there and will update if I finde a good reason not to include it. 
Else I would extend the config file in the next update.

**Comment by bhermann** [comment]
We should come to a final conclusion here and go with the configuration from there.

**Comment by janniclas** [comment]
We just talked about it in our delphi group meeting. We decided to close the issue right now and work with the styles we defined up to now. After actually working with these styles for a month or so we will reevaluate the style settings and reopen this issue if necessary.
