### ISSUE TITLE
Inconsistent behavior of frontend tests

### ISSUE THREAD

**Issue by janniclas** [delphi-hub/delphi-management#91]
**Describe the bug**
Sometimes the angular tests executed with ng test on the travis build pipeline fail and upon rerunning the pipeline the tests are successful. This might be caused due to the random executing order of the test causing some unwanted behavior (which shouldn't be there in any case). This needs further investigation.

**Comment by Ayybeeshafi** [comment]
I figured out that failing of test is not random. Whichever test succeeded `DashboardOverviewComponent should create`testcase it failed. We are using RouterModule in this testcase. I presume that this component couldn't be removed before next test or something like that.
My solution for this problem was calling
`fixture.destroy()` in `afterEach` in spec of DashboardOverviewComponent.
Tests are executing fine on the build pipeline as well as my machine.
